filename: packages/polaris-icons/CHANGELOG.md
inProgressMessage: missing an entry in CHANGELOG.md
skipLabel: skip changelog
detailsUrl: https://github.com/Shopify/polaris-tokens/blob/master/CHANGELOG.md
