name: polaris-tokens

up:
  - ruby:
      version: 2.6.3
  - node:
      version: v10.18.0
      yarn: true
  - bundler
commands:
  test:
    run: yarn run test
  start:
    run: yarn run build
  server:
    run: yarn run watch
