---
name: polaris-tokens

up:
  - ruby:
      version: 2.3.4
  - node:
      version: v8.9.4
      yarn: true
  - bundler
commands:
  test:
    run: yarn test
  start:
    run: yarn dist
  server:
    run: yarn watch
